version: "3"
services:
  app:
    container_name: adonisDocker
    image: mateusbzerra/adonisjs
    command: npm start
    ports:
      - "3333:3333"
    links:
      - "db:db"
    volumes:
     - .:/usr/app
    depends_on:
      - db
  db:
    container_name: adonisDB
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"


